apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml -o ./kubernetes/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-api
  name: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml -o ./kubernetes/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/todo-fullstack-backend: "true"
        io.kompose.network/todo-fullstack-frontend: "true"
        io.kompose.service: todo-api
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/todoDB
          image: todo-api
          name: todo-api
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: todo-api-claim0
      restartPolicy: Always
      volumes:
        - name: todo-api-claim0
          persistentVolumeClaim:
            claimName: todo-api-claim0
status: {}
