apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml -o ./kubernetes/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-api
  name: todo-api
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    io.kompose.service: todo-api
status:
  loadBalancer: {}
